/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ob_android_Pipe */

#ifndef _Included_ob_android_Pipe
#define _Included_ob_android_Pipe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ob_android_Pipe
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mathieu_alloclient_Pipe_open
  (JNIEnv *, jobject);

/*
 * Class:     ob_android_Pipe
 * Method:    closeOutput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mathieu_alloclient_Pipe_closeOutput
  (JNIEnv *, jobject);

/*
 * Class:     ob_android_Pipe
 * Method:    closeInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mathieu_alloclient_Pipe_closeInput
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
